# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [5]:
print(np.version.version)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saksh/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/saksh/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saksh/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

#### 3. Create a null vector of size 10

In [6]:
def null_array(n):
    x = np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
arr = np.array([1,2,3,4,5])
arr_size = arr.size
arr_item_size = arr.itemsize
print(arr_size * arr.itemsize)

20


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [10]:
#from command line -> python -c "import numpy; numpy.info(numpy.add)"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [12]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
z = np.arange(1,11)
z = z[::-1]
print(z)

[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [17]:
nz = np.nonzero( [1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [19]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
z = np.random.random((3,3,3))
print(z)

[[[0.13705998 0.8249907  0.1930853 ]
  [0.29948717 0.10036224 0.93730487]
  [0.35473099 0.9158906  0.01518503]]

 [[0.51924608 0.56859404 0.62336207]
  [0.0532163  0.16524036 0.57452105]
  [0.01090594 0.42107062 0.50874068]]

 [[0.76230516 0.03249526 0.15397949]
  [0.85421761 0.82090842 0.10664602]
  [0.85592351 0.82243555 0.250656  ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
z = np.random.random((10,10))
print(z)
print(np.min(z))
print(np.max(z))

[[0.71614151 0.37469968 0.54008484 0.15820911 0.43651432 0.23573392
  0.05290847 0.63128514 0.87350473 0.51996627]
 [0.09511827 0.1291339  0.64446423 0.41164695 0.56560736 0.74372035
  0.20245203 0.06483719 0.80150704 0.26283988]
 [0.87154008 0.57680657 0.35080859 0.02641355 0.6850308  0.78941171
  0.32361786 0.76716176 0.29356252 0.40852102]
 [0.72175396 0.54165815 0.57215567 0.10620156 0.22448156 0.13992729
  0.7583432  0.17573677 0.09112433 0.44304612]
 [0.7465732  0.59026566 0.44196762 0.93657492 0.77108571 0.64103863
  0.68308167 0.09244447 0.32000044 0.37615471]
 [0.52539216 0.44247544 0.11390255 0.65646594 0.54003655 0.54628087
  0.61300351 0.49220898 0.39850209 0.18479989]
 [0.54507201 0.26252764 0.60797601 0.93626549 0.37857647 0.04954475
  0.6724887  0.47512195 0.94854911 0.76528366]
 [0.10183133 0.90690075 0.88271373 0.82713899 0.2628313  0.02746546
  0.90532576 0.11389262 0.47077431 0.46238792]
 [0.01889659 0.96367789 0.59768887 0.14875007 0.52194721 0.50740369
  0.00678178

#### 14. Create a random vector of size 30 and find the mean value

In [25]:
z = np.random.random(30)
print(z)
print(np.mean(z))

[0.38593401 0.02218197 0.12277023 0.86786117 0.47585425 0.13161054
 0.04516876 0.20117775 0.3334852  0.48296365 0.90125098 0.78955145
 0.81494298 0.63277087 0.39026687 0.06260946 0.64379527 0.36963003
 0.89489092 0.68095006 0.40881795 0.74627414 0.68573705 0.86112031
 0.64808267 0.47424313 0.78505833 0.17030421 0.79178267 0.36724133]
0.5062776074560925


#### 15. Create a 2d array with 1 on the border and 0 inside

In [27]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [8]:
z = np.ones((10,10))
m,n = z.shape
b = np.pad(z, pad_width=1, mode='constant', constant_values=0)


print(z)
print()
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
z = np.diag([1,2,3,4,5],k=-1)
print(z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [18]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [19]:
print (np.unravel_index(1, (2,2)))

(0, 1)
